{
 "title": "ML-Processing",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "detector_job",
    "query": {
     "query": "label_values(ml_processing_detector_messages_processed_created, job)"
    }
   },
   {
    "name": "encoder_job",
    "query": {
     "query": "label_values(ml_processing_encoder_messages_processed_created, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Video Chunk FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg((increase(ml_processing_detector_chunk_fps_sum{job=~\"$detector_job\"}[$__rate_interval]) != 0) / on(job) increase(ml_processing_detector_chunk_fps_count{job=~\"$detector_job\"}[$__rate_interval]))",
     "legendFormat": "FPS"
    }
   ]
  },
  {
   "title": "Detection Class Distribution (Last 5m)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(le) (increase(ml_processing_detector_detection_labels_bucket{job=~\"$detector_job\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Encoder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Messages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(ml_processing_encoder_messages_processed_total{job=~\"$encoder_job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Steps Duration",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(stage) (increase(ml_processing_encoder_processing_duration_seconds_sum{job=~\"$encoder_job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Detector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Messages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(ml_processing_detector_messages_processed_total{job=~\"$detector_job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Steps Duration",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(stage) (increase(ml_processing_detector_processing_duration_seconds_sum{job=~\"$detector_job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Detections Per Frame",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "det/frame" } },
   "targets": [
    {
     "expr": "sum(((increase(ml_processing_detector_detections_count_sum{job=~\"$detector_job\"}[$__rate_interval]) != 0) / on(job) increase(ml_processing_detector_detections_count_count{job=~\"$detector_job\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Detections Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "det/sec" } },
   "targets": [
    {
     "expr": "sum(rate(ml_processing_detector_detections_count_sum{job=~\"$detector_job\"}[$__rate_interval]))",
     "legendFormat": "dps"
    }
   ]
  }
 ]
}